"""add payment fields and change currency to EGP

Revision ID: ab1ec37edaed
Revises: 
Create Date: 2026-06-15 00:21:55.219251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1ec37edaed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_knowledge', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('school_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_activities_school_id'), ['school_id'], unique=False)

    with op.batch_alter_table('school_grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_grades_school_id'), ['school_id'], unique=False)

    with op.batch_alter_table('school_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_media_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_media_status'), ['status'], unique=False)

    with op.batch_alter_table('school_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_services_school_id'), ['school_id'], unique=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('instapay_phone',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('instapay_phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('school_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_services_school_id'))

    with op.batch_alter_table('school_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_media_status'))
        batch_op.drop_index(batch_op.f('ix_school_media_school_id'))

    with op.batch_alter_table('school_grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_grades_school_id'))

    with op.batch_alter_table('school_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_activities_school_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    with op.batch_alter_table('ai_knowledge', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
